# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-10 22:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.CharField(max_length=150)),
                ('data', models.DateTimeField(max_length=100)),
                ('hora_init', models.TimeField(max_length=100)),
                ('hora_fin', models.TimeField(max_length=100)),
                ('procedimento', models.TextField(max_length=400)),
                ('data_criacao', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('data_alteracao', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
