# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-10 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_auto_20171210_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='data',
            field=models.DateTimeField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='hora_fin',
            field=models.TimeField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='hora_init',
            field=models.TimeField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='procedimento',
            field=models.TextField(blank=True, max_length=400),
        ),
    ]
